### ISSUE TITLE
GetFirmwareType Unsupported on Windows 7

### ISSUE THREAD

**Issue by diablolot53** [diablolot53/uefi-checkscript#1]
The script fails to run on Windows 7 with the following error message:

`Exception calling "GetFirmwareType" with "0" argument(s): "Unable to find an entry point named 'GetFirmwareType' in DLL 'kernel32.dll'."`

This is a known issue since the GetFirmwareType API call is not supported on Windows 7. 
Will need to make the following changes:
- Add an OS check to the Get-BiosType function
- Add a UEFI check that is compatible with Windows 7

**Comment by diablolot53** [comment]
Added a UEFI check compatible with Windows 7

**Comment by josephernest** [comment]
I just found your issue. By what should one replace `GetFirmwareType` to make it work on Windows 7?
